config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :subcategories
  root to: redirect("dashboard")
  
  get 'analyse/index', as: :analyse
  get 'analyse/overview', as: :overview

  resources :tags
  get 'import/index', as: :import
  post 'import/upload', as: :upload
  get 'dashboard', as: :dashboard, controller: :dashboard, action: :index

  get "expenses/merge/:e1/:e2", controller: :expenses, action: :merge, as: :merge_expense
  get "expenses/duplicates"
  resources :expenses
  
  resources :tags
  resources :categories

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :expenses
  belongs_to :user
  validates :category, presence: true
  validates :name, presence: true
  validates :name, uniqueness: {scope: :category}
  default_scope { where( user_id: User.logged_in )}
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subcategory, only: [:show]

  # GET /subcategories
  # GET /subcategories.json
  def index
    params.permit(:category_id)
    if params[:category_id]
      @subcategories = Subcategory.where(category_id: params[:category_id])
    else
      @subcategories = Subcategory.all
    end
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
    @q = Expense.where(category: @subcategory.category, subcategory: @subcategory).ransack(params[:q])
    @expenses = @q.result(distinct: true).includes(:category, :subcategory, :tags).order(:date)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/index.html.haml
%h1 Listing subcategories

%table
  %thead
    %tr
      %th Name
      %th Category
      %th
      %th
      %th

  %tbody
    - @subcategories.each do |subcategory|
      %tr
        %td= subcategory.name
        %td= subcategory.category
        %td= link_to 'Show', subcategory
        %td= link_to 'Edit', edit_subcategory_path(subcategory)
        %td= link_to 'Destroy', subcategory, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subcategory', new_subcategory_path

app/views/subcategories/show.html.haml
.col-sm-9
  %h1.page-header
    = image_tag 'subcategory.png', size: "50x50" 
    = @subcategory.name
    %small
      Category:
      = @subcategory.category.name
.col-sm-3
  %br
  %br
  %br
  .btn-group
    = link_to 'To Category', category_path(@subcategory.category), class: "btn btn-primary"
    = link_to 'Edit', edit_category_path(@subcategory.category), class: "btn btn-warning"
    = link_to 'Export', "#", class: "btn btn-info"

= render partial: 'expenses_table'