config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :subcategories
  root to: redirect("dashboard")
  
  get 'analyse/index', as: :analyse
  get 'analyse/overview', as: :overview

  resources :tags
  get 'import/index', as: :import
  post 'import/upload', as: :upload
  get 'dashboard', as: :dashboard, controller: :dashboard, action: :index

  get "expenses/merge/:e1/:e2", controller: :expenses, action: :merge, as: :merge_expense
  get "expenses/duplicates"
  resources :expenses
  
  resources :tags
  resources :categories

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :expenses
  belongs_to :user
  default_scope { where( user_id: User.logged_in )}
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    params[:view] = params[:view] || 'table'
    case params[:view]
    when 'chart'
      @expenses = @tag.expenses
      @categories = Category.order(:name)
      @categories_names = @categories.map{ |c| c.name }
      @data = [] 
      @categories.each do |c|
        subcategories = c.subcategories.order(:name)
        subcategory_names = subcategories.map{|s| s.name}
                            .append "No subcategory"
        subcategory_data = subcategories.map{ |s| @expenses.where(category: c, subcategory: s).map{|e| e.amount}.sum.to_f }
                            .append @expenses.where(category: c,subcategory: nil).map {|e| e.amount}.sum.to_f
        @data.append( 
          { y: @expenses.where(category: c).map{|e| e.amount}.sum.to_f,
            drilldown: {
              name: c.name,
              subcategories: subcategory_names,
              data: subcategory_data
            }
          })
      end
      render :show_chart
    when 'table'
      @q = Expense.joins(:tags).where('tags.id' => @tag).ransack(params[:q])
      @expenses = @q.result(distinct: true).includes(:category, :subcategory, :tags).order(:date)
      render :show_table
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/tags/_show_header.html.haml
.col-sm-9
  %h1.page-header
    = image_tag 'tag.png', size: "50x50" 
    = @tag.name
    %small
      = @tag.expenses.count
      Expenses
.col-sm-3
  %br
  %br
  %br
  .btn-group
    = link_to 'Table', tag_path(@tag, view: :table), class: "btn btn-primary #{'active' if params[:view] == 'table'}"
    = link_to 'Chart', tag_path(@tag, view: :chart), class: "btn btn-primary #{'active' if params[:view] == 'chart'}"

    = link_to 'Edit', edit_tag_path(@tag), class: "btn btn-warning"
    = link_to 'Export', "#", class: "btn btn-info"

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
.col-sm-10
  %h1.page-header
    = @tags.count
    Tags
.col-sm-2
  %br
  %br
  %br
  = link_to 'New Tag', new_tag_path, class: "btn btn-primary"

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Expenses
      %th Amount
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= link_to tag.name, tag
        %td= tag.expenses.count
        %td= number_to_currency tag.expenses.map{|e| e.amount}.sum
        %td
          = link_to 'Edit', edit_tag_path(tag), class: "btn btn-xs btn-warning"
          = link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
.col-sm-10
  %h1.page-header
    Tag: 
    = @tag.name
    %small
      = @tag.expenses.count
      Expenses
.col-sm-2
  %br
  %br
  %br
  = link_to 'Edit', "#", class: "btn btn-warning"
  = link_to 'Export', "#", class: "btn bt-info"


%table.table.table-hover.table-condensed
  %thead
    %tr
      %th
      %th Date
      %th To
      %th Note
      %th Category
      %th Subcategory
      %th Tags
      %th Amount
      %th
  %tbody
    - @tag.expenses.order(:date).each do |expense|
      %tr
        %td= source_image expense.source
        %td= expense.date
        %td= expense.to
        %td= expense.note
        %td
          - if expense.category
            = link_to expense.category.name, expense.category
        %td
          - if expense.subcategory
            = link_to expense.subcategory.name, expense.subcategory
        %td= expense.tags.map {|t| link_to t.name, t }.join(", ").html_safe
        %td= number_to_currency expense.amount
        %td
          = link_to 'Edit', edit_expense_path(expense), class: 'btn btn-xs btn-warning'
          = link_to 'Destroy', expense, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

app/views/tags/show_chart.html.haml
=render partial: "show_header"

#donutchart{style: "width:100%; height:500px;"}
:javascript
  $(function () {
    var colors = Highcharts.getOptions().colors,
        categories = #{@categories_names},
        data = #{@data.to_json},
        bla =[{
            y: 55.11,
            color: colors[0],
            drilldown: {
                name: 'MSIE versions',
                subcategories: ['MSIE 6.0', 'MSIE 7.0', 'MSIE 8.0', 'MSIE 9.0'],
                data: [10.85, 7.35, 33.06, 2.81],
                color: colors[0]
            }
        }, {
            y: 21.63,
            color: colors[1],
            drilldown: {
                name: 'Firefox versions',
                subcategories: ['Firefox 2.0', 'Firefox 3.0', 'Firefox 3.5', 'Firefox 3.6', 'Firefox 4.0'],
                data: [0.20, 0.83, 1.58, 13.12, 5.43],
                color: colors[1]
            }
        }, {
            y: 11.94,
            color: colors[2],
            drilldown: {
                name: 'Chrome versions',
                subcategories: ['Chrome 5.0', 'Chrome 6.0', 'Chrome 7.0', 'Chrome 8.0', 'Chrome 9.0',
                    'Chrome 10.0', 'Chrome 11.0', 'Chrome 12.0'],
                data: [0.12, 0.19, 0.12, 0.36, 0.32, 9.91, 0.50, 0.22],
                color: colors[2]
            }
        }, {
            y: 7.15,
            color: colors[3],
            drilldown: {
                name: 'Safari versions',
                subcategories: ['Safari 5.0', 'Safari 4.0', 'Safari Win 5.0', 'Safari 4.1', 'Safari/Maxthon',
                    'Safari 3.1', 'Safari 4.1'],
                data: [4.55, 1.42, 0.23, 0.21, 0.20, 0.19, 0.14],
                color: colors[3]
            }
        }, {
            y: 2.14,
            color: colors[4],
            drilldown: {
                name: 'Opera versions',
                subcategories: ['Opera 9.x', 'Opera 10.x', 'Opera 11.x'],
                data: [ 0.12, 0.37, 1.65],
                color: colors[4]
            }
        }],
        browserData = [],
        versionsData = [],
        i,
        j,
        dataLen = data.length,
        drillDataLen,
        brightness;


    // Build the data arrays
    for (i = 0; i < dataLen; i += 1) {

        // add browser data
        browserData.push({
            name: categories[i],
            y: data[i].y,
            color: data[i].color
        });

        // add version data
        drillDataLen = data[i].drilldown.data.length;
        for (j = 0; j < drillDataLen; j += 1) {
            brightness = 0.2 - (j / drillDataLen) / 5;
            versionsData.push({
                name: data[i].drilldown.subcategories[j],
                y: data[i].drilldown.data[j],
                color: Highcharts.Color(data[i].color).brighten(brightness).get()
            });
        }
    }

    // Create the chart
    $('#donutchart').highcharts({
        chart: {
            type: 'pie'
        },
        title: {
            text: ''
        },
        yAxis: {
            title: {
                text: 'Total percent market share'
            }
        },
        plotOptions: {
            pie: {
                shadow: false,
                center: ['50%', '50%']
            }
        },
        tooltip: {
            valueSuffix: ' Euro'
        },
        series: [{
            name: 'Categories',
            data: browserData,
            size: '60%',
            dataLabels: {
                formatter: function () {
                    return this.y > 5 ? this.point.name : null;
                },
                color: 'white',
                distance: -30
            }
        }, {
            name: 'Subcategories',
            data: versionsData,
            size: '80%',
            innerSize: '60%',
            dataLabels: {
                formatter: function () {
                    // display only if larger than 1
                    return this.y > 1 ? '<b>' + this.point.name + ':</b> ' + this.y + ' Euro'  : null;
                }
            }
        }]
    });
  });
  

app/views/tags/show_table.html.haml
= render partial: "show_header"

= render partial: "expenses_table"