config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :subcategories
  root to: redirect("dashboard")
  
  get 'analyse/index', as: :analyse
  get 'analyse/overview', as: :overview

  resources :tags
  get 'import/index', as: :import
  post 'import/upload', as: :upload
  get 'dashboard', as: :dashboard, controller: :dashboard, action: :index

  get "expenses/merge/:e1/:e2", controller: :expenses, action: :merge, as: :merge_expense
  get "expenses/duplicates"
  resources :expenses
  
  resources :tags
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :expenses
  has_many :subcategories
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user
  belongs_to :user
  default_scope { where( user_id: User.logged_in )}
  
  def average
    monthly_sums = self.expenses.group_by{ |e| e.date.strftime("%Y-%m") }.map{|m,l| l.map{|e|e.amount}.sum.to_f }
    (monthly_sums.sum / monthly_sums.length)
  end  
  
  def subcategory_list
    self.subcategories.map {|s| s.name}.join(", ")
  end
  
  def subcategory_list=(new_value)
    subcategory_names = new_value.split(/,\s+/)
    self.subcategories = subcategory_names.map { |name| Subcategory.where(category: self, name: name).first or Subcategory.create(category: self, name: name)} 
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.includes(:subcategories).order(:name)
    @subcategories = Subcategory.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    params[:view] = params[:view] || 'table'
    case params[:view]
    when 'chart'
      @months = Expense.where.where(category: @category).map {|e| e.date}.map{ |d| d.strftime("%Y-%m") }.uniq.sort()
      @expenses_series_per_subcategory = []
      @category.subcategories.each do |s|
        subcategory = {name: s.name, data: []}
        @months.each do |month|
          expenses = @category.expenses.where(subcategory: s).where("strftime('%Y-%m', date) = ?", month)
          subcategory[:data].append(expenses.map {|e| e.amount }.sum.to_f)
        end
        @expenses_series_per_subcategory.append subcategory
      end
      subcategory = {name: "No subcategory", data: []}
      @months.each do |month|
          expenses = @category.expenses.where(subcategory: nil).where("strftime('%Y-%m', date) = ?", month)
          subcategory[:data].append(expenses.map {|e| e.amount }.sum.to_f)
        end
        @expenses_series_per_subcategory.append subcategory
      render :show_chart
    when 'table'
      @q = Expense.where(category: @category).ransack(params[:q])
      @expenses = @q.result(distinct: true).includes(:category, :subcategory, :tags).order(:date)
      render :show_table
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :subcategory_list)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
.col-sm-4
  = form_for @category do |f|
    - if @category.errors.any?
      #error_explanation
        %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
        %ul
          - @category.errors.full_messages.each do |msg|
            %li= msg
  
    .field.form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .field.form-group
      = f.label :Subcategories
      = f.text_field :subcategory_list, class: 'form-control'
    .actions
      = f.submit 'Save', class: "btn btn-success"

app/views/categories/_show_header.html.haml
.col-sm-9
  %h1.page-header
    = image_tag 'category.png', size: "50x50"  
    = @category.name
    %small= @category.subcategory_list
.col-sm-3.well
  .btn-group
    %button.btn{disabled: true}
      View:
    = link_to 'Table', category_path(@category, view: :table), class: "btn btn-primary #{'active' if params[:view] == 'table'}"
    = link_to 'Chart', category_path(@category, view: :chart), class: "btn btn-primary #{'active' if params[:view] == 'chart'}"
  %br
  %br
  .btn-group
    %button.btn{disabled: true}
      Actions:
    = link_to 'Edit', edit_category_path(@category), class: "btn btn-warning"
    = link_to 'Export', "#", class: "btn btn-info"

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.col-sm-10
  %h1.page-header
    = @categories.count
    Categories
    %small
      = @subcategories.count
      Subcategories
.col-sm-2
  %br
  %br
  %br
  = link_to 'New Category', new_category_path, class: "btn btn-primary"

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Subcategories
      %th Expenses
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.name, category
        %td
          = category.subcategories.map {|s| link_to s.name, s}.join(", ").html_safe
        %td= category.expenses.count
        %td
          = link_to 'Edit', edit_category_path(category), class: "btn btn-xs btn-warning"
          = link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
.col-sm-10
  %h1.page-header
    Category: 
    = @category.name
    %small= @category.subcategory_list
.col-sm-2
  %br
  %br
  %br
  = link_to 'Edit', edit_category_path(@category), class: "btn btn-warning"
  = link_to 'Export', edit_category_path(@category), class: "btn bt-info"


%table.table.table-hover.table-condensed
  %thead
    %tr
      %th
      %th Date
      %th To
      %th Note
      %th Category
      %th Subcategory
      %th Tags
      %th Amount
      %th
  %tbody
    - @category.expenses.order(:date).each do |expense|
      %tr
        %td= source_image expense.source
        %td.nowrap{style: "min-width: 80px;"}
          = expense.date
        %td= expense.to
        %td= expense.note
        %td
          - if expense.category
            = link_to expense.category.name, expense.category
        %td
          - if expense.subcategory
            = link_to expense.subcategory.name, expense.subcategory
        %td= expense.tags.map {|t| link_to t.name, t }.join(", ").html_safe
        %td= number_to_currency expense.amount
        %td
          = link_to 'Edit', edit_expense_path(expense), class: 'btn btn-xs btn-warning'
          = link_to 'Destroy', expense, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

app/views/categories/show_chart.html.haml
=render partial: 'show_header'

#barchart{style: "width:100%; height:500px;"}
:javascript
  $(function () {
    $('#barchart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: #{@months}
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Expenses'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
  
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
            }
        },
        series: #{@expenses_series_per_subcategory.to_json}
    });
  });

app/views/categories/show_table.html.haml
= render partial: 'show_header'

= render partial: 'expenses_table'