config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :subcategories
  root to: redirect("dashboard")
  
  get 'analyse/index', as: :analyse
  get 'analyse/overview', as: :overview

  resources :tags
  get 'import/index', as: :import
  post 'import/upload', as: :upload
  get 'dashboard', as: :dashboard, controller: :dashboard, action: :index

  get "expenses/merge/:e1/:e2", controller: :expenses, action: :merge, as: :merge_expense
  get "expenses/duplicates"
  resources :expenses
  
  resources :tags
  resources :categories

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @q = Expense.ransack(params[:q])
    @expenses = @q.result(distinct: true).includes(:category, :subcategory, :tags).order(:date)
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.source = :webapp
    respond_to do |format|
      if @expense.save
        format.html { redirect_to :back, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to :back, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { redirect :back}
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def duplicates
    @set1 = Expense.includes(:tags, :category, :subcategory).all
    @set2 = Expense.includes(:tags, :category, :subcategory).all
    
    @duplicates = []
    @set1.each_with_index do |e1, index1|
      @set2.each_with_index do |e2, index2|
        if index1 < index2
          if e1.date == e2.date and e1.amount == e2.amount
            if e1.source == e2.source
              if e1.to == e2.to and e1.note == e2.note
                @duplicates.append([e1,e2])
              end
            else
              @duplicates.append([e1,e2])
            end
          end
        end
      end
    end
  end
  
  def merge
    @e1 = Expense.find_by_id params[:e1]
    @e2 = Expense.find_by_id params[:e2]
    if not @e1 and @e2
      redirect_to :expenses_duplicates, notice: 'One of the selected expenses does not exist anymore.'
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:amount, :to, :note, :category_id, :subcategory_id, :date, :tag_list)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  
  def source_image source
    case source
    when 'ing'
      return image_tag 'ING.png', size: "16x16"
    when 'dkb_giro'
      return image_tag 'dkb.png', size: "16x16"
    when 'dkb_credit'
      return image_tag 'visa2.jpg', size: "16x10"
    when 'sparkasse'
      return image_tag 'sparkasse.png', size: "16x16"
    when 'excel'
      return image_tag 'Excel.png', size: "16x16"
    when 'webapp'
      return image_tag 'favicon.png', size: "16x16"
    when 'android'
      return image_tag 'android.png', size: "16x16"
    else
      return ""
    end
  end
end

app/views/expenses/_form.html.haml
.col-sm-4
  = form_for @expense, html: {class: 'form-horizontal'} do |f|
    - if @expense.errors.any?
      #error_explanation
        %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
        %ul
          - @expense.errors.full_messages.each do |msg|
            %li= msg
    .field.form-group
      .col-sm-12
        = f.label :date
        %br
        = f.date_select :date, {}, {class: 'form-control date-select'}
    .field.form-group
      .col-sm-12
        = f.label :amount
        = f.number_field :amount, class: 'text_field form-control', step: 0.01
    .field.form-group
      .col-sm-12
        = f.label :to
        = f.text_field :to, class: 'form-control'
    .field.form-group
      .col-sm-12
        = f.label :note
        = f.text_field :note, class: 'form-control'
    .field.form-group
      .col-sm-6
        = f.label :category
        = f.collection_select :category_id, Category.all.order(:name), :id, :name, {}, {class: 'form-control'}
      :javascript
        $("#expense_category_id").click(function(){
          var url = '/subcategories.json?category_id=' + $(this).val()
          $("#expense_subcategory_id").children('option:not(:first)').remove();
          $.get(url, function(data) {
            $.each(data, function(index, category) {
              console.log(index, category) 
              $('#expense_subcategory_id')
                   .append($("<option></option>")
                   .attr("value",category.id)
                   .text(category.name));
            });
          });
        });
      .col-sm-6
        = f.label :subcategory
        = f.collection_select :subcategory_id, Subcategory.where(category: @expense.category).order(:name), :id, :name, {include_blank: true}, {class: 'form-control'}
    .field.form-group
      .col-sm-12
        = f.label :tags
        = f.text_field :tag_list, class: 'form-control'
    .actions
      = f.submit 'Save', class: 'btn btn-success'

app/views/expenses/duplicates.html.haml
.col-sm-10
  %h1.page-header
    = @duplicates.count
    Possible Duplicates
.col-sm-2
  %br
  %br
  %br
  = link_to 'Export', "#", class: "btn btn-info"

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th
      %th
      %th Date
      %th To
      %th Note
      %th Category
      %th Subcategory
      %th Tags
      %th Amount
      %th
  %tbody
    - @duplicates.each do |e1,e2|
      %tr
        %td
          = source_image e1.source
          %br
          = source_image e2.source
        %td 
          =e1.id
          %br
          =e2.id
        %td= e1.date
        %td
          = e1.to
          %br
          = e2.to
        %td
          = e1.note
          %br
          = e2.note
        %td
          = link_to e1.category.name, e1.category
          %br
          = link_to e2.category.name, e2.category
        %td
          - if e1.subcategory
            = link_to e1.subcategory.name, e1.subcategory
          %br
          - if e2.subcategory
            = link_to e2.subcategory.name, e2.subcategory
        %td
          = e1.tags.map {|t| link_to t.name, t}.join(", ").html_safe
          %br
          = e2.tags.map {|t| link_to t.name, t}.join(", ").html_safe
        %td= number_to_currency e1.amount
        %td
          = link_to 'Edit', edit_expense_path(e1), class: 'btn btn-xs btn-warning'
          = link_to 'Destroy', e1, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'
          = link_to 'Merge', merge_expense_path(e1, e2), class: 'btn btn-sm btn-info'
          = link_to 'Edit', edit_expense_path(e2), class: 'btn btn-xs btn-warning'
          = link_to 'Destroy', e2, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

app/views/expenses/edit.html.haml
%h1 Editing expense

= render 'form'

= link_to 'Show', @expense
\|
= link_to 'Back', expenses_path

app/views/expenses/index.html.haml
.col-sm-10
  %h1.page-header
    = @expenses.count
    Expenses
.col-sm-2
  %br
  %br
  %br
  = link_to 'New Expense', new_expense_path, class: "btn btn-primary"

= render partial: 'expenses_table'

app/views/expenses/merge.html.haml
.col-md-10
  %h1.page-header Merging expenses
.col-md-2
  %br
  %br
  %br
  = link_to "Back to duplicates", :expenses_duplicates, class: "btn btn-primary"


.col-sm-1
.col-sm-4
  - if @e1
    = form_for @e1, html: {class: 'form-horizontal'} do |f|
      - if @e1.errors.any?
        #error_explanation
          %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
          %ul
            - @e1.errors.full_messages.each do |msg|
              %li= msg
      .field.form-group
        .col-sm-12
          = f.label :date
          %br
          = f.date_select :date, {disabled: true}, {class: 'form-control date-select'}
      .field.form-group
        .col-sm-12
          = f.label :amount
          = f.number_field :amount, disabled: true, class: 'form-control'
      .field.form-group
        .col-sm-12
          = f.label :to
          = f.text_field :to, class: 'form-control'
      .field.form-group
        .col-sm-12
          = f.label :note
          = f.text_field :note, class: 'form-control'
      .field.form-group
        .col-sm-6
          = f.label :category
          = f.collection_select :category_id, Category.all.order(:name), :id, :name, {}, {class: 'form-control', id: "expense_category_id_1"}
        :javascript
          $("#expense_category_id_1").click(function(){
            var url = '/subcategories.json?category_id=' + $(this).val()
            $("#expense_subcategory_id_1").children('option:not(:first)').remove();
            $.get(url, function(data) {
              $.each(data, function(index, category) {
                console.log(index, category) 
                $('#expense_subcategory_id_1')
                     .append($("<option></option>")
                     .attr("value",category.id)
                     .text(category.name));
              });
            });
          });
        .col-sm-6
          = f.label :subcategory
          = f.collection_select :subcategory_id, Subcategory.where(category: @e1.category).order(:name), :id, :name, {include_blank: true}, {class: 'form-control', id: "expense_subcategory_id_1"}
      .field.form-group
        .col-sm-12
          = f.label :tags
          = f.text_field :tag_list, class: 'form-control'
      .actions
        = f.submit 'Save', class: 'btn btn-success'
        = link_to 'Destroy', @e1, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'


.col-sm-2


.col-sm-4
  -if @e2
    = form_for @e2, html: {class: 'form-horizontal'} do |f|
      - if @e2.errors.any?
        #error_explanation
          %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
          %ul
            - @e2.errors.full_messages.each do |msg|
              %li= msg
      .field.form-group
        .col-sm-12
          = f.label :date
          %br
          = f.date_select :date, {disabled: true}, {class: 'form-control date-select'}
      .field.form-group
        .col-sm-12
          = f.label :amount
          = f.number_field :amount, disabled: true, class: 'form-control'
      .field.form-group
        .col-sm-12
          = f.label :to
          = f.text_field :to, class: 'form-control'
      .field.form-group
        .col-sm-12
          = f.label :note
          = f.text_field :note, class: 'form-control'
      .field.form-group
        .col-sm-6
          = f.label :category
          = f.collection_select :category_id, Category.all.order(:name), :id, :name, {}, {class: 'form-control', id: "expense_category_id_2"}
        :javascript
          $("#expense_category_id_2").click(function(){
            var url = '/subcategories.json?category_id=' + $(this).val()
            $("#expense_subcategory_id_2").children('option:not(:first)').remove();
            $.get(url, function(data) {
              $.each(data, function(index, category) {
                console.log(index, category) 
                $('#expense_subcategory_id_2')
                     .append($("<option></option>")
                     .attr("value",category.id)
                     .text(category.name));
              });
            });
          });
        .col-sm-6
          = f.label :subcategory
          = f.collection_select :subcategory_id, Subcategory.where(category: @e2.category).order(:name), :id, :name, {include_blank: true}, {class: 'form-control', id: "expense_subcategory_id_2"}
      .field.form-group
        .col-sm-12
          = f.label :tags
          = f.text_field :tag_list, class: 'form-control'
      .actions
        = f.submit 'Save', class: 'btn btn-success'
        = link_to 'Destroy', @e2, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/expenses/new.html.haml
%h1 New expense

= render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.haml
%p#notice= notice

%p
  %b To:
  = @expense.to
%p
  %b Note:
  = @expense.note
%p
  %b Category:
  = link_to @expense.category.name, @expense.category
  
%p
  %b Subcategory:
  - if @expense.subcategory
    = link_to @expense.subcategory.name, @expense.subcategory
%p
  %b Date:
  = @expense.date

= link_to 'Edit', edit_expense_path(@expense)
\|
= link_to 'Back', expenses_path